type Query {
    accountsList : [BankAccount]
    getAccountById(id : String) : BankAccount
}

type Mutation {
    createAccount(bankAccount : BankAccountRequestDTO) : BankAccountResponseDTO
    updateAccount(id : String, bankAccount : BankAccountRequestDTO) : BankAccountResponseDTO
    deleteAccount(id : String) : Boolean
}

type BankAccount {
    id : String,
    createdAt : String,
    balance : Float,
    currency : String,
    type : String
    customer : Customer
}

type Customer{
    id : ID,
    name : String,
    bankAccounts : [BankAccount]
}

type BankAccountResponseDTO {
    id : String,
    createdAt : String,
    balance : Float,
    currency : String,
    type : String
    customer : Customer
}

input BankAccountRequestDTO {
    balance : Float,
    currency : String,
    type : String
    customerId : String
}

 