type Query {
    accountsList : [BankAccount]
    getAccountById(id : String) : BankAccount
    getCustomerById(id : String) : Customer
    customerList : [Customer]
}

type Mutation {
    createAccount(bankAccount : BankAccountRequestDTO) : BankAccountResponseDTO
    updateAccount(id : String, bankAccount : BankAccountRequestDTO) : BankAccountResponseDTO
    deleteAccount(id : String) : Boolean
    saveCustomer(customer : CustomerRequestDTO) : CustomerResponseDTO
    updateCustomer(id : ID, customer : CustomerRequestDTO) : CustomerResponseDTO
    deleteCustomer(id : ID) : Boolean
}

type BankAccount {
    id : String,
    createdAt : String,
    balance : Float,
    currency : String,
    type : String
    customer : Customer
}

type Customer{
    id : ID,
    name : String,
    bankAccounts : [BankAccount]
}

type BankAccountResponseDTO {
    id : String,
    createdAt : String,
    balance : Float,
    currency : String,
    type : String
    customer : Customer
}

input BankAccountRequestDTO {
    balance : Float,
    currency : String,
    type : String
    customerId : String
}

type CustomerResponseDTO {
    id : ID,
    name : String,
    bankAccounts : [BankAccountResponseDTO]
}

input CustomerRequestDTO {
    name : String
}